
language: cpp
os:
  - linux
complier:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-precise

    packages:
      - cppcheck
      - make
      - cmake
      - clang-format
script:
  - cd ./configs/example/
  - cppcheck --version
  - ./travis_cppcheck.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)